### PR TITLE
Decrease Imperative load time for plugin

### PR DESCRIPTION
**Pull request by tjohnsonBCM**
This PR minimizes the number of files that Node must require when Imperative loads the plugin config. On my machine, it decreases the time to load the plugin config from ~500 ms to <10 ms.

### CODE REVIEW

**Comment by zFernand0** [comment]
This could be done across the entire repo (and other repositories as well) 😸 
Nice idea!

**Comment by tjohnsonBCM** [comment]
> This could be done across the entire repo (and other repositories as well) 😸

Although we could do this elsewhere, there seem to have been reasons in the past why we discouraged plugins from using specific imports.

So for now, it seems to make sense to only change to using specific imports in the plugin's Imperative config file, because of the resulting performance improvement.

**Comment by sosadchuk** [comment]
@zFernand0 @t1m0thyj Hey guys, could you please share how you measured the load time? Wanted to verify if this kind of change will have any effect in our project.

I checked `imperative.log` output
- from`[DEBUG] [PluginManagementFacility.js:130] PluginManagementFacility.init() - Start`
- to `[INFO] [Imperative.js:251] Inherited traits applied to CLI command tree children. Cmd tree details at trace level of logging.`

**Comment by t1m0thyj** [comment]
@sosadchuk To measure the load time, you can use the method described in [this Medium article](https://medium.com/zowe/migrating-zowe-cli-plug-ins-for-v2-conformance-c538d75fd860):
> You can test the load time of your plug-in by running the following command in the root directory of your plug-in project. The command caches Imperative in memory and evaluates how long it takes to load your plug-in:
> ```
> node -e "require('[@zowe/imperative](http://twitter.com/zowe/imperative)'); console.time(); require('./lib/imperative.js'); console.timeEnd();"
> ```

**Pull request merged**
