### PR TITLE
Updated dependencies

### LINKED ISSUE #72: Failing Vulnerabilities Check in pipeline
Dependency `typedoc` needs updating to recent version in package.json in order to pass vulnerabilities check in Jenkins pipeline.

### PR DESCRIPTION
**Pull request by AndrewTwydell**
Resolves #72.

Updated TypeDoc dependency which was breaking the vulnerabilities check in Jenkins.
Also updated the Ts-Jest dependency that created a low vulnerability warning.

### CODE REVIEW

**Review by t1m0thyj — APPROVED** [review]
Thanks for updating 👍 Not sure why the vuln check was failing as it's only supposed to scan non-dev dependencies. 🤷 

Not necessary to update the changelog for this PR, since the changes aren't user-facing. Adding the "no-changelog" label to a PR makes the build pass without needing a changelog. 

I'm ok with merging this PR as is, the unnecessary line in changelog can be removed when these changes are merged into #70 or #71. 🙂

**Comment by AndrewTwydell** [comment]
Thanks for reviewing @t1m0thyj. I also thought it was weird that it was scanning dev dependencies, although it seems the CLI repo also scans them and flags any vulnerabilities. 

As for the change-log, I'm happy to go through and take out the entry, but if you're happy removing it when merging then that saves me a job 😃

**Comment by t1m0thyj** [comment]
@AndrewTwydell Merged #66 first and now there is a conflict, sorry about that 😢 Could you please merge with latest changes in master branch and update the changelog?

**Comment by AndrewTwydell** [comment]
@t1m0thyj No worries, I've merged master into this branch and removed my entry from the change-log. All checks passed, is there anything else you need me to do??

**Comment by t1m0thyj** [comment]
LGTM 🙂

**Pull request merged**
