### PR TITLE
Migrate to zowe namespace

### LINKED ISSUE #12: Test with Typescript 3.2.2
Hello,

Please test upgrading typescript in your devDependencies to version to 3.2.2. When testing, please use the version of  imperative and zowe CLI tagged `@typescript3` on bintray which have been compiled with the same version. Verify that you can still compile and run your plug-in's commands. This will ensure your plugin will be compatible with a future update to zowe CLI and imperative that uses the new typescript version.

If all looks well after your testing, you can merge the change into your master branch

### LINKED ISSUE #17: Migrate DB2 plugin to @zowe namespace

### PR DESCRIPTION
**Pull request by ChrisBoehmCA**
Fix #17 

Migrate the plugin to `@zowe` namespace (change package name to `@zowe/db2` and import from `@zowe/imperative` instead of `@brightside/imperative`). These changes are only for the master/ latest branch and can't be ported to lts-incremental as the package name change is breaking and `@zowe/cli` and `@zowe/imperative` will only be available  on the `@daily` and `@latest` tags

Also Fix #12

I wasn't able to run the unit tests. I get a lot of errors like this: 

```
 Error
      Error: The specified module could not be found.
      \\?\C:\nodejs\zowe-cli-db2-plugin\node_modules\ibm_db\build\Release\odbc_bindings.node
```

Could @nurra01  or @vasev01  please check out this branch and see if you're able to run the unit tests and any other tests you have?

### CODE REVIEW

**Comment by nurra01** [comment]
I have cloned and run npm install, and got this error:
Capture

**Comment by nurra01** [comment]
and tests are failing with the same error you had

**Comment by ChrisBoehmCA** [comment]
Hmm, that seems related to the ibm db driver. Do you get the same error on master (I get the same failing tests on master)? I don't think I did anything that would affect the db driver

**Comment by nurra01** [comment]
I got the same. Have you tried it in Linux ?

**Comment by ChrisBoehmCA** [comment]
I have not. I can try later to see if it works on Linux

**Comment by vasev01** [comment]
Chris, I can install and run unit tests under Linux. Only tests in `DB2Sessions.test.ts` are failing due to missed `SESSION.username` field.

**Comment by vasev01** [comment]
db2install
db2test-unit

**Comment by ChrisBoehmCA** [comment]
I updated the unit tests. Hopefully that fixes it

**Comment by ChrisBoehmCA** [comment]
OK. The tests all passed on Linux for me just now.   Is the driver installation just harder on Windows? I don't think the failure was introduced by this PR since it also fails on master for me but maybe somebody should look into the Windows failures

**Pull request merged**
