### PR TITLE
Node 14 update

### PR DESCRIPTION
**Pull request by awharn**

### CODE REVIEW

**Comment by zFernand0** [comment]
I'm wondering why we are seeing failures with low dev-dep vulnerabilities if the command is `npm audit --production --audit-level=moderate`.

**Review by zFernand0 — APPROVED** [review]
LGTM!

**Review by t1m0thyj — APPROVED** [review]
LGTM.

I think this should be a patch release, since that's what we did when ibm_db was updated for Node 12.

**Comment by zFernand0** [comment]
then, should the changelog say patch instead of enhancement? 
I'm just being annoying here, so no need to change it 😋

**Review by zFernand0 — APPROVED** [review]
Thank you! 😋

**Comment by zFernand0** [comment]
bypassing vuln check since it's just dev deps (which shouldn't have been flagged)
Merging...

**Pull request merged**
