### PR TITLE
Lts update

### PR DESCRIPTION
**Pull request by nurra01**
Update lts-incremental branch with pull request #13 . Shouldn't break existing functionality.

### CODE REVIEW

**Comment by nurra01** [comment]
yes, that --host and --user refactor is in "latest" branch.

**Comment by nurra01** [comment]
Ready to be merge if there are no other comments. I run tests all of them passed in Linux machine. In windows it doesn't work because of odbc driver installation problems.

**Comment by ChrisBoehmCA** [comment]
Should somebody look into the windows problems with the driver installation? Maybe open an issue? Ideally the tests should pass on Windows and Linux

**Comment by vasev01** [comment]
I'm looking into it. The problem is, probably, with node-gyp and MS build tools.

**Comment by ChrisBoehmCA** [comment]
OK. Thank you

**Pull request merged**
