### PR TITLE
65 table export

### LINKED ISSUE #65: Export table does not generate statement separator
The current version does NOT generate an ‘end-of-statement’ character.  As a result, the output file would have to be edited in order for it to be useful with for example zowe excute sql to use the generated statements. Perhaps it makes sense to add an option to generate or suppress the option.

### PR DESCRIPTION
**Pull request by AndrewTwydell**
Resolves #65.

This PR inserts a semicolon(;) in-between each of the INSERT statements produced by the `zowe db2 export table` command. 

The `zowe db2 execute sql` command allows the user to string together multiple statements using a semicolon(;) as a separator, therefore these changes allow the results of exporting a table to be reused in execution, as mentioned in #65.

Note: This branch is built on top of #70 (PR to resolves incorrect snapshots and testing) so should not be merged before that branch.

### CODE REVIEW

**Review by t1m0thyj — APPROVED** [review]
Nice simple solution, LGTM 👍 

@MikeBauerCA Is there any concern about this being a breaking change, if plugin users have been consuming the output of `export table` in a script? Or is this considered a bug fix because the statements were previously missing a required character?

**Comment by MikeBauerCA** [comment]
For the next major LTS release of Zowe, we should make this the default behavior. 

However, for backwards compatibility we should introduce this behavior through a flag. I'm leaning towards introducing a `--separator` flag that would be `false` by default to preserve existing behavior, but could be easily added on a command to resolve #65.

**Comment by Joe-Winchester** [comment]
I was talking to a customer who ran into the https://github.com/zowe/zowe-cli-db2-plugin/issues/65 issue.  Is there anything I can do to help get this delivered ?  Tks

**Comment by AndrewTwydell** [comment]
Hi @Joe-Winchester, it was decided this needs to be added to an optional flag to prevent this being a breaking change, however I am yet to push the update. I will get it done this week. 👍

**Comment by AndrewTwydell** [comment]
@MikeBauerCA @t1m0thyj I think I've added this feature to an optional flag, please double check / re-review etc, and we can chat about it Monday! 😀 

FYI - @Joe-Winchester

**Comment by AndrewTwydell** [comment]
[Zowe CLI DB2 Plugin Issues](https://trello.com/c/mlyQYABX/24-zowe-cli-db2-plugin-issues)

**Review by zFernand0 — APPROVED** [review]
LGTM!
😋

**Pull request merged**
